name = "quiz-worker"
main = "worker/src/index.js"
compatibility_date = "2026-06-26"

# D1数据库绑定（创建后替换database_id）
[[d1_databases]]
binding = "DB"
database_name = "quiz-db"
database_id = "ce712cc6-8e7e-49e7-82a6-29ed5962dabe"
